name: verifast-proof-diff
on:   [pull_request, push]
jobs:
  proof_diff:
    runs-on:  ubuntu-latest
    steps:
      - run: |
          pwd
          ls
          ls Test/VeriFast/tasks/vTaskSwitchContext/
      - run: Test/VeriFast/tasks/vTaskSwitchContext/diff.sh `pwd`
